services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    branch: main
    buildCommand: ""
    startCommand: uvicorn nfc_backend_fastapi.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: DATABASE_URL
        value: <we will fill this in later>
